### ISSUE TITLE
redmine 3.4.2 error. undefined method `get_project_data' 

### ISSUE THREAD

**Issue by Jiangshan00001** [redminehappiestminds/redmine_issues_from_excel#6]
Started GET "/redmine/projects/cpcszq/import_from_excel" for 192.168.1.188 at 2017-08-02 17:55:15 +0800
Processing by ImportFromExcelController#index as HTML
  Parameters: {"name_prefix"=>"project", "project_id"=>"cpcszq"}
  Current user: xxx(id=4)
Completed 500 Internal Server Error in 158ms (ActiveRecord: 41.7ms)

NoMethodError (undefined method `get_project_data' for #<ImportFromExcelController:0x007f565beca050>
Did you mean?  edit_project_path):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by juneyoung** [comment]
got same issue here. I am using 3.3. 

```
NoMethodError (undefined method `get_project_data' for #<ImportFromExcelController:0x00000005f1a0b8>):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by xamp** [comment]
I got same issue on 3.4.2 

```
Started GET "/redmine/projects/15pl-033/import_from_excel" for 192.168.1.1 at 2017-09-13 18:15:19 +0900
Processing by ImportFromExcelController#index as HTML
  Parameters: {"name_prefix"=>"project", "project_id"=>"15pl-033"}
  Current user: myid (id=5)
Completed 500 Internal Server Error in 117ms (ActiveRecord: 1.6ms)

NoMethodError (undefined method `get_project_data' for #<ImportFromExcelController:0x007f46f9849e18>
Did you mean?  edit_project_path):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

```

**Comment by mbalecr7** [comment]
Same issue on 3.2

**Comment by lindhor** [comment]
and same on 3.4.4. This is the same as issue #7

**Comment by M0d3rn15t** [comment]
Has anyone got the favourite projects plugin installed?

I have the same issue. Similar issues with other plugins has been down to favourite projects.

This plugin and some others change how the project data is presented which may affect some project data calls.

**Comment by l00193629** [comment]
I'm using Redmine 3.4.5, i got the same problem.

Unfortunately, i seems there is no plan to fix it...
