### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by paedae93** [redminehappiestminds/redmine_issues_from_excel#7]
Hello,

I wanted to use your plugin but when I press the link "import issues from excel" I come to an error page.
![image](https://user-images.githubusercontent.com/5691568/31430975-af6043fc-ae72-11e7-8f76-c5d4155453f6.png)

I did the setup like you described it:
![image](https://user-images.githubusercontent.com/5691568/31431123-12da8b2c-ae73-11e7-8bb8-ba288db49ac4.png)

And i have a supported version:
![image](https://user-images.githubusercontent.com/5691568/31430940-9c08b9f6-ae72-11e7-9964-ab00c726e90d.png)

Do you have any suggestion what i have done wrong?

Best regards and thanks
Patrick

**Comment by redminehappiestminds** [comment]
Please share the error log f

**Comment by szakipecs** [comment]
hi!

I have the same problem.
I tried to install iconv gem, but it fails every time, so a solution without iconv would be great!

Thanks in advance

Log:

Started GET "/projects/kaposvaramraram/import_from_excel" for xxx.xxx.xxx.xxx at 2017-11-02 14:59:15 +0100

LoadError (cannot load such file -- iconv):
  plugins/redmine_issues_from_excel/app/controllers/import_from_excel_controller.rb:13:in `<class:ImportFromExcelController>'
  plugins/redmine_issues_from_excel/app/controllers/import_from_excel_controller.rb:1:in `<top (required)>'


Started GET "/projects/kaposvaramraram/import_from_excel" for xxx.xxx.xxx.xxx at 2017-11-02 15:28:35 +0100
Processing by ImportFromExcelController#index as HTML
  Parameters: {"name_prefix"=>"project", "project_id"=>"kaposvaramraram"}
  Current user: xxxxxx (id=6)
Completed 500 Internal Server Error in 140ms (ActiveRecord: 46.8ms)

NoMethodError (undefined method `get_project_data' for #<ImportFromExcelController:0x0000000c7e7730>
Did you mean?  edit_project_path):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'


Started GET "/projects/ede?jump=issues" for xxx.xxx.xxx.xxx at 2017-11-02 15:30:04 +0100
Processing by ProjectsController#show as HTML
  Parameters: {"jump"=>"issues", "id"=>"ede"}
  Current user: xxxxx (id=6)
Redirected to http://xxxxxxx:3001/projects/ede/issues
Completed 302 Found in 62ms (ActiveRecord: 62.4ms)
Started GET "/projects/ede/issues" for xxx.xxx.xxx.xxx at 2017-11-02 15:30:04 +0100
Processing by IssuesController#index as HTML
  Parameters: {"project_id"=>"ede"}
  Current user: xxxxx (id=6)
  Rendered queries/_filters.html.erb (31.2ms)
  Rendered queries/_columns.html.erb (0.0ms)
  Rendered queries/_query_form.html.erb (31.2ms)
  Rendered issues/_list.html.erb (46.8ms)
  Rendered plugins/redmine_issues_from_excel/app/views/issues/_import_issues_from_excel.html.erb (0.0ms)
  Rendered issues/_sidebar.html.erb (15.6ms)
  Rendered issues/index.html.erb within layouts/base (93.6ms)
  Rendered plugins/redmine_xlsx_format_issue_exporter/app/views/hooks/_insert_xlsx_link_for_dialog.erb (0.0ms)
  Rendered plugins/redmine_xlsx_format_issue_exporter/app/views/hooks/_xlsx_export_dialog_on_issues_index.erb (0.0ms)
Completed 200 OK in 218ms (Views: 140.8ms | ActiveRecord: 0.0ms)
Started GET "/projects/pecsamraram" for xxx.xxx.xxx.xxx at 2017-11-02 15:30:13 +0100
Processing by ProjectsController#show as HTML
  Parameters: {"id"=>"pecsamraram"}
  Current user: xxxxx (id=6)
  Rendered projects/_members_box.html.erb (0.0ms)
  Rendered projects/show.html.erb within layouts/base (15.6ms)
Completed 200 OK in 156ms (Views: 47.8ms | ActiveRecord: 78.0ms)
Started GET "/projects/pecsamraram/issues?set_filter=1&tracker_id=6" for xxx.xxx.xxx.xxx at 2017-11-02 15:30:16 +0100
Processing by IssuesController#index as HTML
  Parameters: {"set_filter"=>"1", "tracker_id"=>"6", "project_id"=>"pecsamraram"}
  Current user: xxxxx (id=6)
  Rendered queries/_filters.html.erb (31.2ms)
  Rendered queries/_columns.html.erb (0.0ms)
  Rendered queries/_query_form.html.erb (31.2ms)
  Rendered plugins/redmine_issues_from_excel/app/views/issues/_import_issues_from_excel.html.erb (0.0ms)
  Rendered issues/_sidebar.html.erb (0.0ms)
  Rendered issues/index.html.erb within layouts/base (46.8ms)
  Rendered plugins/redmine_xlsx_format_issue_exporter/app/views/hooks/_insert_xlsx_link_for_dialog.erb (0.0ms)
  Rendered plugins/redmine_xlsx_format_issue_exporter/app/views/hooks/_xlsx_export_dialog_on_issues_index.erb (0.0ms)
Completed 200 OK in 250ms (Views: 87.6ms | ActiveRecord: 124.8ms)
Started GET "/projects/pecsamraram/import_from_excel" for xxx.xxx.xxx.xxx at 2017-11-02 15:30:20 +0100
Processing by ImportFromExcelController#index as HTML
  Parameters: {"name_prefix"=>"project", "project_id"=>"pecsamraram"}
  Current user: xxxxx (id=6)
Completed 500 Internal Server Error in 109ms (ActiveRecord: 31.2ms)

NoMethodError (undefined method `get_project_data' for #<ImportFromExcelController:0x0000000ea55b50>
Did you mean?  edit_project_path):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by mbalecr7** [comment]
Hi i have the same problem, please correct that

**Comment by lindhor** [comment]
Also the same problem. I use redline 3.4.4 with Ruby 2.4.2 and apache 2.4.6 on CentOS 7.4. I get the following in the log as an admin after I set up the plugin permissions.
```
App 21155 stderr: Started GET "/redmine/projects/cockpit/import_from_excel" for 10.0.2.2 at 2018-02-23 12:19:47 +0100
App 21155 stderr: Processing by ImportFromExcelController#index as HTML
App 21155 stderr:   Parameters: {"name_prefix"=>"project", "project_id"=>"cockpit"}
App 21155 stderr:   Current user: RLI (id=11)
App 21155 stderr: Completed 500 Internal Server Error in 96ms (ActiveRecord: 2.0ms)
App 21155 stderr: 
App 21155 stderr: NoMethodError (undefined method `get_project_data' for #<ImportFromExcelController:0x00007f3923483ab0>
App 21155 stderr: Did you mean?  edit_project_path):
App 21155 stderr:   lib/redmine/sudo_mode.rb:63:in `sudo_mode'
App 21155 stderr: 
App 21155 stderr: 
```
